### ISSUE TITLE
d3-graphviz SVG output different from local Graphviz tool for large graphs.

### ISSUE THREAD

**Issue by pxantos** [magjac/d3-graphviz#116]
Hello, I'm currently trying to use d3-graphviz to visualize data trees that will hold some IDs. These trees are usually very wide, with most of the nodes being direct children of the root node. The problem is that when I run the attached html script using d3-graphviz, the nodes heavily overlap and are unreadable. When I convert that exact digraph into an SVG with my local graphviz tool, I get the correct expected tree, which I have also attached.

In the zip file attached are the html file using d3-graphviz as well as the correct expected SVG. The data in these files is all placeholder data. Do you have any recommendations? 

I really appreciate any help!

-Pablo

[d3-graphviz-TooLarge.zip](https://github.com/magjac/d3-graphviz/files/3553009/d3-graphviz-TooLarge.zip)

**Comment by magjac** [comment]
Sadly, I can only confirm that I'm getting the same results as you.

I tried to upgrade the viz.js and d3-graphviz versions. That didn't help. I then tried to downgrade d3 to v4. That didn't help either:
```
<script src="https://d3js.org/d3.v4.js"></script>
<script src="https://unpkg.com/viz.js@1.8.2/viz.js" type="application/javascript"></script>
<script src="https://unpkg.com/d3-graphviz@2.6.1/build/d3-graphviz.js"></script>
```
You might want to use [viz.js](https://github.com/mdaines/viz.js/) directly to see if the problem is viz.js or the d3-graphviz additions. If that doesn't work either, you might want to try viz.js v2.x that d3-graphviz does not yet support (#55) or https://github.com/hpcc-systems/hpcc-js-wasm that it does not yet support either (#111).

Please let me know how it goes if you try any of them.

**Comment by pxantos** [comment]
So I tried directly using Viz.js 2.1.2 as well as using https://github.com/hpcc-systems/hpcc-js-wasm, but still had the same problem.

Thanks for responding!

**Comment by magjac** [comment]
This is not an issue in d3-graphviz itself.
