### ISSUE TITLE
resetZoom() does not work after rendering the second graph if transition is not used

### ISSUE THREAD

**Issue by Polad10** [magjac/d3-graphviz#151]
I am trying to reset zoom and fit to the view dynamically generated graphs. However, it works only for the first graph. The next rendered graph is not displayed correctly (not fitting to the view). 

Here is an example https://jsfiddle.net/pw2fquga/2/. Try to render the graphs by clicking on buttons in any order.

**Comment by magjac** [comment]
Thank for supplying an executable example :slightly_smiling_face:.

I can't get it to work though. First, nothing happened when pressing the button.  After changing `<button onclick="handleButtonClick">` to `<button onclick="handleButtonClick()">` it still doesn't work, because no dot argument is supplied. Maybe you forgot to save the latest version?

**Comment by Polad10** [comment]
I have updated the graph after submitting the issue :). Please check this link https://jsfiddle.net/pw2fquga/2/ .

**Comment by magjac** [comment]
Thanks. Yes, you seem to have actually found a bug. I added a transition and then it seems to work: https://jsfiddle.net/jdg78cpe/.

I hope you can use that as a workaround until I've fixed it.

**Comment by Polad10** [comment]
Thank you!

**Comment by magjac** [comment]
BTW, if you're a Graphviz and DOT fan, please join the new Graphviz forum at https://graphviz.discourse.group/. It's still daringly empty, but we hope people will join and contribute.

**Comment by magjac** [comment]
Fixed in version [3.0.6](https://github.com/magjac/d3-graphviz/blob/master/CHANGELOG.md#306).
