### ISSUE TITLE
graphviz.on() implementation is unintuitive and confusing

### ISSUE THREAD

**Issue by broofa** [magjac/d3-graphviz#182]
Thank you so much for producing this module.  I'm using it on https://npm.broofa.com and it's been great.  (I mean that.  This isn't just the usual, "be nice before being mean" pleasantry.  Thank you!)

That said, I just spent the better part of my morning trying to figure out why my code that was subscribing multiple 'end' event listeners wasn't working.  It was only after carefully reading the docs that I discovered I needed to be adding a unique suffix for each listener function ('end.log', 'end.showLoader', 'end.finalize', etc.). 

To say I was surprised is putting it mildly.  More like...

![image](https://media4.giphy.com/media/11ahZZugJHrdLO/giphy.gif)

Why on earth does this work this way?!?  `on()` is... well... `on()`!  It's a standard method with a well understood behavior ("Add a listener for 'X'").  Having a different behavior ("Add a listener for 'X' while unsubscribing previous listeners") sets a nasty trap for unsuspecting developers.  Also, having to concoct a unique suffix for each listener is an unnecessary annoyance.

Please either rename the method to something else ('onSuffixedEvent'?) to indicate users should not expect the standard EventEmitter behavior or, better, bring the implementation in line with EventEmitter's `on()` method.

**Comment by magjac** [comment]
Thanks for the kind words a the link to your cool project. :slightly_smiling_face: 

The behavior is modeled on [d3-transition.on()](https://github.com/d3/d3-transition#transition_on) and like that library uses [d3-dispatch.on()](https://github.com/d3/d3-dispatch#dispatch_on). Since d3-graphviz is a D3 plugin, I think it makes sense to have the same behavior. If you don't like it, I suggest you file an issue at https://github.com/d3/d3-dispatch/issues/new.
