### ISSUE TITLE
DOT-to-DOT transition: Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by GrahamHannington** [magjac/d3-graphviz#22]
(I couldn't resist writing "DOT-to-DOT" in the title.)

Transitioning from one DOT to another causes this error (latest Chrome on Windows 10, graphviz v1.1.0):

d3-graphviz.js:622 Uncaught TypeError: Cannot read property 'x' of undefined
    at convertToPathData (d3-graphviz.js:622)
    at extractData (d3-graphviz.js:730)
    at SVGPathElement.<anonymous> (d3-graphviz.js:755)
    at S.each (d3.v4.min.js:2)
    at extractData (d3-graphviz.js:745)
    at SVGAElement.<anonymous> (d3-graphviz.js:755)
    at S.each (d3.v4.min.js:2)
    at extractData (d3-graphviz.js:745)
    at SVGGElement.<anonymous> (d3-graphviz.js:755)
    at S.each (d3.v4.min.js:2)

The problem surfaces here:

    var bbox = guideData.bbox;
    bbox.cx = bbox.x + bbox.width / 2;

`bbox` is undefined.

This error only occurs for some DOT files. Any idea what the problem might be?

**Comment by GrahamHannington** [comment]
Probably more appropriate in an new issue, but I'm here... sometimes, when the DOT-to-DOT animation _does_ work, I don't get a clean render of the new DOT when the transition is done; the view includes "junk" (such as filled wedges) left over from the old DOT.

**Comment by magjac** [comment]
Please provide a complete test case that illustrates the problem. Also please specify which Chrome version you are using, `latest` is perishable.

If you do indeed think this is a bug in d3-graphviz, please post here. Otherwise [Stack Overflow tags d3.js & graphviz](https://stackoverflow.com/tags/d3.js+graphviz) is a better place.

Thanks for submitting this issue. If you are using this library, don't forget to "Watch" it to stay tuned for updates or even "Star" it if you like it.

You can also use [Stack Overflow tags d3.js & graphviz](https://stackoverflow.com/tags/d3.js+graphviz) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [JSFiddle](https://jsfiddle.net/). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.
