### ISSUE TITLE
rotate=90 graph attribute does not set the rotation

### ISSUE THREAD

**Issue by reregaga** [magjac/d3-graphviz#251]
`rotate=90` graph attribute does not set the rotation, instead the rendered image disappears during typing this attribute or if you refresh the page, the graph is drawn as if without the `rotate` attribute.

[Example](http://magjac.com/graphviz-visual-editor/?dot=digraph%20%7B%0D%0A%20%20%20%20rotate%3D90%0D%0A%20%20%20%20a%5Bwidth%3D2%5D%0D%0A%7D):
```
digraph {
    //rotate=90 //uncomment
    a[width=2]
}
```

**Comment by magjac** [comment]
The problem is in [translateZoomBehaviorTransform](https://github.com/magjac/d3-graphviz/blob/b15c28a9024763294885e10767c0cdd9a4c3e891/src/zoom.js#L71-L87) which doesn't handle rotation, but assumes it is zero. If the call to that function is removed, the problem doesn't occur.

This means that a workaorund when using d3-graphviz directly is to disable zooming with `.zoom(false)`. Unfortunatley there's no way to do this in the [Graphviz Visual Editor](https://github.com/magjac/graphviz-visual-editor) for which this problem was originally reported.

**Comment by magjac** [comment]
> The problem is in [translateZoomBehaviorTransform](https://github.com/magjac/d3-graphviz/blob/b15c28a9024763294885e10767c0cdd9a4c3e891/src/zoom.js#L71-L87) which doesn't handle rotation, but assumes it is zero. If the call to that function is removed, the problem doesn't occur.
> 
> This means that a workaorund when using d3-graphviz directly is to disable zooming with `.zoom(false)`. Unfortunatley there's no way to do this in the [Graphviz Visual Editor](https://github.com/magjac/graphviz-visual-editor) for which this problem was originally reported.

There was also a similar problem with transitions. See https://github.com/magjac/d3-graphviz/pull/328 for details.
