### ISSUE TITLE
How do I trap errors in the DOT?

### ISSUE THREAD

**Issue by GrahamHannington** [magjac/d3-graphviz#27]
How do I trap errors in the DOT; that is, the `data` that I pass to `d3.select("#graph").graphviz().renderDot(data, myRenderDOTEndFunction)`?

I've read the the following in the viz.js readme:

> If Graphviz encounters an error, Viz will throw an Error object with the error message.

and I've looked at the d3-graphviz code that calls Viz, but I can't yet figure out how to trap errors in the input DOT that I pass to d3-graphviz.

I see that the Graphviz object returned by `d3.select("#graph").graphviz().renderDot(data, myRenderDOTEndFunction)` contains a `_worker` property, and `_worker` contains an `onerror` property that has the value `null`. I suspect I need to set that property.

I could burn time trying to figure out what to do next—I'm enjoying improving my JavaScript coding skills—but I need to crack on with other work.

P.S. I really like d3-graphviz. Thank you so much for this. I'm using d3-graphviz for what is, so far, a small internal-use-only project, but I hope to get management approval to publish my project as a GitHub repo, which will, effectively, be a showcase for d3-graphviz.

**Comment by magjac** [comment]
Thanks @GrahamHannington. I think I will have to add an [.onerror](https://developer.mozilla.org/en-US/docs/Web/API/AbstractWorker/onerror) listener [here](https://github.com/magjac/d3-graphviz/blob/master/src/dot.js#L215). I will look into it on Sunday. If you can't wait, you're welcome to give it a try.

**Comment by magjac** [comment]
Since the layout is done asynchronously in a web worker, any caught error must be sent back to the application through some kind of callback. I've tried the patch below and it works in Firefox, but not in Chrome. It adds an `.onerror` method to d3-graphviz which you can use like this:

```
d3.select("#graph").graphviz()
        .onerror(error)
        .renderDot('{bad dot}');

function error(err) {
    console.log('Caught error:', err);
}

```diff --git a/src/dot.js b/src/dot.js
index 380e2ab..78362f8 100644
--- a/src/dot.js
+++ b/src/dot.js
@@ -218,6 +218,13 @@ export default function(src, callback) {
                 return layoutDone.call(graphvizInstance, event.data.svg);
             }
         };
+        worker.onerror = function(error) {
+            if (graphvizInstance._onerror) {
+                graphvizInstance._onerror(error);
+            } else {
+                throw error.message
+            }
+        };
     } else {
         layoutDone.call(this, Viz(src, vizOptions));
     }
diff --git a/src/graphviz.js b/src/graphviz.js
index d653009..d36b0e0 100644
--- a/src/graphviz.js
+++ b/src/graphviz.js
@@ -20,6 +20,7 @@ import growEnteringEdges from "./growEnteringEdges";
 import zoom from "./zoom";
 import {resetZoom} from "./zoom";
 import on from "./on";
+import onerror from "./onerror";
 import logEvents from "./logEvents";

 export function Graphviz(selection) {
@@ -114,5 +115,6 @@ Graphviz.prototype = graphviz.prototype = {
     active: active,
     attributer: attributer,
     on: on,
+    onerror: onerror,
     logEvents: logEvents,
 };
diff --git a/src/onerror.js b/src/onerror.js
new file mode 100644
index 0000000..353d401
--- /dev/null
+++ b/src/onerror.js
@@ -0,0 +1,6 @@
+export default function(callback) {
+
+    this._onerror = callback
+
+    return this;
+};
```

**Comment by magjac** [comment]
Below is a patch that works in both Chrome and Firefox. I'll make a new release when I have more time.

```diff --git a/src/dot.js b/src/dot.js
index 380e2ab..e6c8ad7 100644
--- a/src/dot.js
+++ b/src/dot.js
@@ -216,6 +216,14 @@ export default function(src, callback) {
             switch (event.data.type) {
             case "done":
                 return layoutDone.call(graphvizInstance, event.data.svg);
+                break;
+            case "error":
+                if (graphvizInstance._onerror) {
+                    graphvizInstance._onerror(event.data.error);
+                } else {
+                    throw event.data.error
+                }
+                break;
             }
         };
     } else {
diff --git a/src/graphviz.js b/src/graphviz.js
index d653009..902cd3b 100644
--- a/src/graphviz.js
+++ b/src/graphviz.js
@@ -20,6 +20,7 @@ import growEnteringEdges from "./growEnteringEdges";
 import zoom from "./zoom";
 import {resetZoom} from "./zoom";
 import on from "./on";
+import onerror from "./onerror";
 import logEvents from "./logEvents";

 export function Graphviz(selection) {
@@ -29,8 +30,16 @@ export function Graphviz(selection) {
                 if (event.data.vizURL) {
                     importScripts(event.data.vizURL);
                 }
-                var svg = Viz(event.data.dot, event.data.options);
-
+                try {
+                    var svg = Viz(event.data.dot, event.data.options);
+                }
+                catch(error) {
+                    postMessage({
+                        type: "error",
+                        error: error.message,
+                    });
+                    return;
+                }
                 if (svg) {
                     postMessage({
                         type: "done",
@@ -114,5 +123,6 @@ Graphviz.prototype = graphviz.prototype = {
     active: active,
     attributer: attributer,
     on: on,
+    onerror: onerror,
     logEvents: logEvents,
 };
diff --git a/src/onerror.js b/src/onerror.js
new file mode 100644
index 0000000..353d401
--- /dev/null
+++ b/src/onerror.js
@@ -0,0 +1,6 @@
+export default function(callback) {
+
+    this._onerror = callback
+
+    return this;
+};
```

**Comment by GrahamHannington** [comment]
`.onerror()` (in v1.3.0) works for me, thank you! (And thank you for the new release.)

**Comment by GrahamHannington** [comment]
With apologies if I should create a separate issue for this: the documentation of `.onerror()` in the readme could be improved by describing, or showing (as per your [example](#issuecomment-352172306)), that the callback function can accept a parameter that contains a string describing the error.  (Unless you think this is the bleeding obvious; I don't, but I'm a JavaScript noob.)

**Comment by magjac** [comment]
Thanks @GrahamHannington. I've updated the README.
