### ISSUE TITLE
labels are not rendered, instead, ids of dot nodes are being rendered

### ISSUE THREAD

**Issue by MatanKoby** [magjac/d3-graphviz#319]
My ids are in the format of 'state-hash'
My labels are names of items.

Since this morning, all nodes show ids instead of showing labels, like in the attached screenshot

![Screenshot 2024-08-14 at 15 37 23](https://github.com/user-attachments/assets/f7054657-2ea5-4e4a-a868-731df011e3f0)

There was a @hpcc-js/wasm update about 9-10 hours ago, and d3-graphviz has it as dependency with on version ^2.16.2, so I suspect it as the culprit.
Please check and fix soon

**Comment by magjac** [comment]
In general, there's no guarantee that using d3-graphviz with another version of @hpcc-js/wasm than what is stated as a dependency in package.json will work. So I recommend that you stick with 2.16.2 until a new release of d3-graphviz that has been verified with the new version of @hpcc-js/wasm has been released.

That said, it seems unlikely that it's a compatibility problem that you are seeing. Since you haven't provided a reproducible test case it's impossible to say what the problem is, but I would not expect it to be in d3-graphviz or @hpcc-js/wasm. Rather in Graphviz itself or in your code. I suggest you try your DOT source with the version of Graphviz that your version of @hpcc-js/wasm uses (presumably 12.1.0). If it works there and you still think it's a problem with d3-graphviz, you're welcome to come back with a reproducible test case and I will look into it.
