### ISSUE TITLE
dashed borders don't disappear

### ISSUE THREAD

**Issue by schloerke** [magjac/d3-graphviz#49]
When setting a node border to dashed, then transitioning to something without a dash, the original dash does not go away.

live example
https://jsfiddle.net/xpvt214o/99139/

**Comment by magjac** [comment]
Thanks for an excellent bug report!

I've reproduced the problem and will investigate a solution shortly.

**Comment by magjac** [comment]
This bug is now fixed in v1.6.1.

Thanks for submitting this issue. If you are using this library, don't forget to **Watch** it to stay tuned for updates or even **Star** it if you like it.

You can also use [Stack Overflow tags d3.js & graphviz](https://stackoverflow.com/tags/d3.js+graphviz) or the [d3-graphviz Slack](https://join.slack.com/t/d3-graphviz/shared_invite/enQtMzMwODQzMDI5MDA5LTExYTgyYThhNzI3YjJlODRiMzQ3MWM3YWI5ZjAyMTI2MmI4YWIwMDM4ZmY5MDQzNjkzMDY4YTRmMTU1YzIzNTY) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly.
