### ISSUE TITLE
D3-selection d3.selectAll('.node') not working anymore

### ISSUE THREAD

**Issue by simojoe** [magjac/d3-graphviz#92]
In this [example](https://bl.ocks.org/magjac/28a70231e2c9dddb84b3b20f450a215f) using d3-graphviz v0.1.2 et viz.js v1.8.0, the command `d3.selectAll('.node')` is used to select all drawn nodes to bind a `.on` element.

Using a simplified version of the code and up-to-date version of d3-graphviz (v2.5.0), the behavior could not be reproduce (see the code at the end of the issue). The selection gives an empty array. However, if one execute the same line in the javascript console in the browser, the correct selection is given.

Is that the normal behavior? If so, how can I achieve a selection of all nodes (or edge) element?

```
<!DOCTYPE html>
<meta charset="utf-8">

<body>
    <script src="https://unpkg.com/d3@5.6.0/dist/d3.min.js"></script>
    <script src="https://unpkg.com/viz.js@1.8.0/viz.js" type="javascript/worker"></script>
    <script src="https://unpkg.com/d3-graphviz@2.5.0/build/d3-graphviz.js"></script>
    <div id="graph" style="text-align: center;"></div>
    <script>
        var dotSrc =
            `
digraph {
    graph [label="This is a graph"]
    Node1 -> Node2
}
`;

        var graphviz = d3.select("#graph").graphviz();

        graphviz
            .renderDot(dotSrc);

        nodes = d3.selectAll('.node,.edge');
        console.log(nodes);
    </script>
```

**Comment by magjac** [comment]
Yes, that is the intended behavior. Because the rendering takes place in the background since [v1.0.0](https://github.com/magjac/d3-graphviz/releases/tag/v1.0.0), the graph elements are not yet available immediately after [renderDot](https://github.com/magjac/d3-graphviz#graphviz_renderDot) returns. When you access them through the JavaScript console in the browser, the rendering has had time to finish and you *can* inspect them.

You need to attach a callback to [renderDot](https://github.com/magjac/d3-graphviz#graphviz_renderDot) (see [this example](https://github.com/magjac/d3-graphviz/blob/master/examples/basic-shape-tween.html#L25)) or an [event handler](https://github.com/magjac/d3-graphviz#graphviz_on) for the `end` event (see [this example](https://github.com/magjac/d3-graphviz/blob/master/examples/demo.html#L25)).

This might look something like:
```
        graphviz
            .renderDot(dot, function () {
                nodes = d3.selectAll('.node,.edge');
                console.log(nodes);
            });
```

Thanks for submitting this issue. If you are using this library, don't forget to **Watch** it to stay tuned for updates or even **Star** it if you like it.

You can also use [Stack Overflow tags d3.js & graphviz](https://stackoverflow.com/tags/d3.js+graphviz) or the [d3-graphviz Slack](https://join.slack.com/t/d3-graphviz/shared_invite/enQtMzMwODQzMDI5MDA5LTExYTgyYThhNzI3YjJlODRiMzQ3MWM3YWI5ZjAyMTI2MmI4YWIwMDM4ZmY5MDQzNjkzMDY4YTRmMTU1YzIzNTY) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly.
